# Generated by Django 2.2.17 on 2021-03-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20210313_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent']},
        ),
    ]
